### PR TITLE
Standalone App and Changes to make Sling Convert

### PR DESCRIPTION
**Pull request by schaefa**
This PR adds a standalone app (picocli) and changes to the PM to FM converter to make Sling PM successfully convert to FM.

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @schaefa this PR looks very good to me. Thanks for all the work. Is there a JIRA related to this work? I think it would be good to have one, so that we can reference it at release time etc.
@karlpauls @cziegeler maybe you can review as well?

**Comment by bosschaert** [comment]
@schaefa I think that once you can share a JIRA number for it we are good then.

**Comment by schaefa** [comment]
@bosschaert This is the JIRA ticket I created for this task: https://issues.apache.org/jira/browse/SLING-8423

**Comment by bosschaert** [comment]
Thanks @schaefa it's merged!

**Pull request merged**
